### Get Task

GET http://localhost:8080/odata/v4/TodoService/task


### Create Task
POST http://localhost:8080/odata/v4/TodoService/task HTTP/1.1
Content-Type : application/json

{
    "task_name" : "Write unit cases for App",
    "task_description"   : "First task for testing ",    
    "priority" : "2",
    "status" : "1",
    "due_by" : "2021-06-28T15:36:56.200"
}


### Update Task
PATCH  http://localhost:8080/odata/v4/TodoService/task(751a16aa-b6b6-496c-ba76-116db1c545ae) HTTP/1.1
Content-Type: application/json

{   
    "task_name" : "Create Purchase Order",
    "task_description" : "First task for testing ",    
    "priority" : "3",
    "status" : "1",
    "due_by" : "2021-06-11T15:36:56.200"
}


###Delete Task
DELETE  http://localhost:8080/odata/v4/TodoService/task(2e753761-7009-4426-9593-66189ef862a5) HTTP/1.1

